[options]
HoldPkg      = pacman glibc
Architecture = auto
ParallelDownloads = 5
SigLevel     = Required DatabaseOptional
LocalFileSigLevel = Optional
Include = /etc/pacman.d/zachos-hold.conf

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
